apiVersion: 1
 
datasources:
  - name: prometheus
    type: prometheus
    uid: befn4bj036x34e  # Specific UID you want to use
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: false
    version: 1
    editable: false

  - name: ${DS_MSSQL}
    type: mssql
    uid: sqlserver_ds    
    access: proxy
    url: ${DB_HOST}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    database: ${DB_NAME}  
    isDefault: false
    editable: true