{
 "title": "Microsoft SQL Server Dashboard",
 "description": "This is a comprehensive Microsoft SQL Server Dashboard designed to monitor key performance indicators. It provides real-time insights into your SQL Server environment",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT sqlserver_start_time as 'SQL SERVER START TIME'\nFROM sys.dm_os_sys_info;\n"
    }
   ]
  },
  {
   "title": "Queries per Second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    qs.total_elapsed_time / qs.execution_count / 1000.0 AS avg_duration_ms,\n    qs.execution_count,\n    SUBSTRING(qt.text, qs.statement_start_offset/2,\n              (CASE\n                  WHEN qs.statement_end_offset = -1 THEN LEN(CONVERT(NVARCHAR(MAX), qt.text)) * 2\n                  ELSE qs.statement_end_offset\n               END - qs.statement_start_offset)/2) AS query_text\nFROM sys.dm_exec_query_stats qs\nCROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) qt\nORDER BY avg_duration_ms DESC;\n"
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    request_session_id AS SessionID,\n    resource_database_id AS DatabaseID,\n    resource_associated_entity_id AS EntityID,\n    request_mode AS LockType,\n    request_status AS Status\nFROM sys.dm_tran_locks;\n"
    }
   ]
  },
  {
   "title": "Buffer Pool Hit Rate",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS BufferPoolUsed_MB,\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS DirtyBuffer_MB,\n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS BufferPoolTotal_MB,\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS DirtyBufferUsed_MB\nFROM sys.dm_os_buffer_descriptors\nWHERE database_id > 4;\n"
    }
   ]
  },
  {
   "title": "Index Usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    OBJECT_NAME(s.object_id) AS TableName,\n    i.name AS IndexName,\n    s.user_seeks,\n    s.user_scans,\n    s.user_lookups,\n    s.user_updates\nFROM sys.dm_db_index_usage_stats AS s\nINNER JOIN sys.indexes AS i ON i.object_id = s.object_id AND i.index_id = s.index_id\nWHERE s.database_id = DB_ID(DB_NAME())\nORDER BY s.user_seeks DESC;\n"
    }
   ]
  },
  {
   "title": "Buffer Pool Usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    (total_physical_memory_kb / 1024) AS Total_Physical_Memory_MB,\n    (available_physical_memory_kb / 1024) AS Available_Physical_Memory_MB,\n    (total_page_file_kb / 1024) AS Total_Page_File_MB,\n    (available_page_file_kb / 1024) AS Available_Page_File_MB,\n    (system_memory_state_desc) AS System_Memory_State_Description\nFROM sys.dm_os_sys_memory;\n"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT COUNT(*) AS Running_Threads\nFROM sys.dm_exec_requests\nWHERE status = 'running';\n"
    }
   ]
  },
  {
   "title": "Table Locks",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    request_session_id AS SessionID,\n    resource_database_id AS DatabaseID,\n    resource_associated_entity_id AS EntityID,\n    request_mode AS LockType,\n    request_status AS Status\nFROM sys.dm_tran_locks;\n"
    }
   ]
  },
  {
   "title": "Open Files Limit",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    COUNT(*) AS OpenFiles\nFROM sys.dm_io_pending_io_requests;\n"
    }
   ]
  },
  {
   "title": "Temp Tables Created On Disk",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    SUM(user_objects_alloc_page_count) AS UserObjectPages,\n    SUM(internal_objects_alloc_page_count) AS InternalObjectPages\nFROM sys.dm_db_session_space_usage;\n"
    }
   ]
  },
  {
   "title": "Query Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT \n    (CAST(SUM(CASE WHEN usecounts > 0 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*)) * 100 AS Cache_Hit_Ratio\nFROM sys.dm_exec_cached_plans\nWHERE objtype = 'Adhoc'\n    OR objtype = 'Prepared';\n"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT COUNT(session_id) AS Connections\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1;\n"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "dataset": "WEM",
     "rawSql": "SELECT TOP 10\n    qs.total_elapsed_time / qs.execution_count / 1000.0 AS avg_duration_ms,\n    qs.execution_count,\n    SUBSTRING(qt.text, qs.statement_start_offset/2,\n              (CASE\n                  WHEN qs.statement_end_offset = -1 THEN LEN(CONVERT(NVARCHAR(MAX), qt.text)) * 2\n                  ELSE qs.statement_end_offset\n               END - qs.statement_start_offset)/2) AS query_text\nFROM sys.dm_exec_query_stats qs\nCROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) qt\nORDER BY avg_duration_ms DESC;\n"
    }
   ]
  }
 ]
}