services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/alerts-and-notifiers.yml:/etc/grafana/provisioning/alerting/alerts-and-notifiers.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GRAFANA_NOTIFICATION_ADDRESSES=${GRAFANA_NOTIFICATION_ADDRESSES}
      - GRAFANA_SMTP_HOST=${GRAFANA_SMTP_HOST}
      - GRAFANA_SMTP_USER=${GRAFANA_SMTP_USER}
      - GRAFANA_SMTP_PASSWORD=${GRAFANA_SMTP_PASSWORD}
      - GRAFANA_SMTP_FROM_ADDRESS=${GRAFANA_SMTP_FROM_ADDRESS}
      - GRAFANA_SMTP_FROM_NAME=${GRAFANA_SMTP_FROM_NAME}
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    restart: always

volumes:
  grafana_data:
  prometheus_data: